### ISSUE TITLE
this.opt.period value is "-" during applet execution, breaking 'show label' (labeltext)

### ISSUE THREAD

**Issue by AtilioA** [raphaelquintao/QRedshiftCinnamon#11]
`this.opt.period` on the right when applet is active:
![image](https://user-images.githubusercontent.com/27153776/88496070-5404d880-cf92-11ea-9dad-df01d2c548c0.png)
My location settings:
![image](https://user-images.githubusercontent.com/27153776/88496077-5a935000-cf92-11ea-807a-c4e4d7bbc19e.png)

This leads to `this.opt.enabledNight && this.opt.period.toLowerCase() == 'night'` being false and label showing day settings despite night mode being active. If I simply remove the `&& this.opt.period.toLowerCase() == 'night'` condition, it works fine (since `this.opt.enabledNight` is `true`).
Is there a reason for needing another check besides `this.opt.enabledNight`? Or perhaps this should be an OR condition instead?

Screenshot depicting the problem:
![image](https://user-images.githubusercontent.com/27153776/88496427-73e8cc00-cf93-11ea-9232-f750c4467135.png)

**Comment by AtilioA** [comment]
> If I simply remove the `&& this.opt.period.toLowerCase() == 'night'` condition, it works fine

Just realized that doing this breaks the label during the day. `enabledNight` refers only to whether QRedshift should have different settings at night, not if it is actually using night settings. Anyways, my problem remains.

**Comment by raphaelquintao** [comment]
You use your Linux in Portuguese that's the problem i guess.
Try change the language to English just to test.

**Comment by AtilioA** [comment]
Yes, it works if I change to English.

**Comment by raphaelquintao** [comment]
I will think in something to fix it!

**Comment by raphaelquintao** [comment]
You can find the step in `this.db_Slider.STEP`.
You really dont need to call `this.doUpdate()` when you emit a value to the slider `this.db_Slider._setValueEmit(newValuenb)` `dayBrightChange` is called. 

Thanks man! You will just keep the keybindings with Control, but of course you can change to alt.

**Comment by raphaelquintao** [comment]
Fixed in version 1.5.2.

I fixed it by `this.opt.enabledNight && this.opt.period.toLowerCase().startsWith("n")`.
I just test if the period string start with n, if true show night info. 
It should work for all language that night start with n, in Portuguese will work fine. 
But will not work for strange languages.
