### ISSUE TITLE
Shorcut conflicts

### ISSUE THREAD

**Issue by gecharita** [raphaelquintao/QRedshiftCinnamon#13]
![image](https://user-images.githubusercontent.com/40850523/91270616-954efa80-e781-11ea-86e0-f030053460c9.png)

After the latest update, the following shortcuts were introduced as default:

- Ctrl + Page Up
- Ctrl + Page Down

Those are the **default shortcuts** for many applications (e.g. Nemo File Explorer, VSCode, Firefox, Chrome) for moving to next/previous tab, thus there are conflicts there.

It was difficult to trace why the shorcuts above, suddenly stopped to work properly.

**Comment by raphaelquintao** [comment]
I will remove the default values on the new version.
I just don't know when the new version will come out. =D

**Comment by raphaelquintao** [comment]
Fixed in version 1.5.3 !
