### ISSUE TITLE
Please implement option for switching night mode based on time

### ISSUE THREAD

**Issue by fermmm** [raphaelquintao/QRedshiftCinnamon#14]
This application helps with sleep disorders so that the light from the screen does not take away the sleep, so it's related with the time someone goes to sleep.
I would like to have an option to activate night mode near the time I go to sleep instead of "at night".

**Comment by FibroJedi** [comment]
Or alternatively set up a schedule. So I gradually reduce brightness and decrease temperature as the evening progresses, in line with what my smart light schedule does. It would be fab to add settings schedules :)

**Comment by raphaelquintao** [comment]
This will come in a future version, of course, not for now, by the way.

**Comment by raphaelquintao** [comment]
Done, in version 1.6.0. 
🍻

**Comment by FibroJedi** [comment]
Thank you so much, super appreciated!
