### ISSUE TITLE
QRedshift only apply color shift to 1 monitor

### ISSUE THREAD

**Issue by t3pfaffe** [raphaelquintao/QRedshiftCinnamon#15]
As in the title only one monitor is being effected. Any idea how to get this to work with multiple monitors? RedShift itself is definitely capable of it.

**Comment by raphaelquintao** [comment]
Temporally you can go to:
`~/.local/share/cinnamon/applets/qredshift@quintao/assets/base.conf` and comment the screen an crtc lines with a `;`

[randr]
;screen=0,1,2
;crtc=0,1,2

Try it, and let me know if works.

**Comment by Samrel556** [comment]
Just tried this. It works

**Comment by trymeouteh** [comment]
Please add a GUI setting to enable/disable multiple monitor use

**Comment by raphaelquintao** [comment]
I could, but its too much work. Maybe i do that some day.
