### ISSUE TITLE
change default keyboard shortcuts

### ISSUE THREAD

**Issue by jonorthwash** [raphaelquintao/QRedshiftCinnamon#22]
After a recent update, I found that I wasn't able to change tabs in my browser, terminal, messaging client, and other programs, using the <kbd>Ctrl</kbd>+<kbd>PgUp</kbd> and <kbd>Ctrl</kbd>+<kbd>PgDn</kbd> shortcuts.

It turned out that during the update, QRedshift overrode those shortcuts without my knowledge—I was able to figure this out only after scouring the internet until I found [someone else who'd had the same problem and managed to figure it out](https://forums.linuxmint.com/viewtopic.php?t=334381).  Like them, I was worried something had broken.

The <kbd>Ctrl</kbd>+<kbd>PgUp</kbd> and <kbd>Ctrl</kbd>+<kbd>PgDn</kbd> shortcuts are the default way to alternate between tabs in nearly every program I've ever used that has tabs (and in many cases it's hard-coded).  QRedshift should _not_ override _any_ system-level keyboard shortcuts, much less these.  At worst it should tell the user that there are new shortcuts available that need to be set.  QRedshift is the sort of program you expect to set up once and ignore unless something changes, and not the sort of program you expect to make it impossible to switch between tabs just because there's a new version.

Note: this functionality was added in #9 based on #8.

**Comment by raphaelquintao** [comment]
I will remove that o next release, was a big mistake... that happens... =D

**Comment by raphaelquintao** [comment]
Fixed https://github.com/raphaelquintao/QRedshift/commit/e78d13da7e158f9891df4e9fdd1ca53a1885ecda#diff-fdf323b43304316f2a5ef56a0fbb6487d222e35617efeb0f8309fb7cdf00c8fc
