### ISSUE TITLE
What would it take to bring this applet to Mate Desktop?

### ISSUE THREAD

**Issue by ghost** [raphaelquintao/QRedshiftCinnamon#24]
What would it take to bring this applet to Mate Desktop?

Or at least: is it possible to add to the applet that already exists in Mate (redshift-gtk) the functionality to change the values with the mouse wheel?

(Sorry for the possible ignorance, I am not a programmer).

**Comment by raphaelquintao** [comment]
I don't think it's possible. Need to rewrite everything from scratch.

**Comment by ghost** [comment]
Obrigado pela sua atenção, e parabéns pelo seu trabalho.
