### ISSUE TITLE
"Redshift not installed"

### ISSUE THREAD

**Issue by Philipp91** [raphaelquintao/QRedshiftCinnamon#25]
My `redshift` installation got updated from `1.12-2+build1` to `1.12-4` around January 14th. Today I rebooted and QRedshift stopped working, it just says "Redshift not installed". I noticed that a QRedshift update was available (`1.5.2`), so I installed that too but the problem remains.

Obviously the suggested fix `apt-get install redshift` doesn't have any effect because it's already installed.

**Comment by raphaelquintao** [comment]
Can you run `redshift -V`  on console and put the output here please.

**Comment by Philipp91** [comment]
```
[1]    160617 segmentation fault  redshift -V
```

Looks like this is https://github.com/jonls/redshift/issues/708. Sorry for the noise.
