### ISSUE TITLE
no refreshment after moving manually cursors bright or temp since Qredshift 1.5.4 (2021-02-24 22:37:53)

### ISSUE THREAD

**Issue by didier-linux** [raphaelquintao/QRedshiftCinnamon#31]
Dear Raphael Quintao,

Thanks a lot for this great application, since I use it, I can't do without. I did an update of the latest version (1.5.4 (2021-02-24 22:37:53) and observed a bug since the update :
first method: changing manually "temp" or "bright" cursors with lclick on mouse, slip and release mouse does not change temp nor bright. After moving the cursor this way, temp or bright are change only after performing a "reload applet"
but, second method,  changing manually "temp" or "bright" cursors by left clicking directly on the cursor bar works to the condition the first method as not been tried before.
Scrolling the mouse on cursor to change bright or temp behaves exactly as slip with the mouse. 
This bug occurs only since the version 1.5.4, and occurs either with day or night cursors. I did not change any options before and after the update. 
I also did what is recommanded on installation, removing a redshift-gtk package and disable redshift ...

* applet version is 1.5.4 (2021-02-24 22:37:53)
* my cinnamon version is : 4.8.6
* my Distribution is Linux MINT Debian Edition LMDE 4 Debbie, this is exactly the same as debian 10 stable with an additionnal MINT repository
* Graphics hardware and driver used : Intel Corporation UHD Graphics 620

 Thanks a lot If you could fix this bug

**Comment by raphaelquintao** [comment]
Hi,
This error don't occurs to me, I  did a clean installation o LMDE 4 to test.
I have no idea whats can be happening to you.
Have you tried change the adjustment method?

Can you make a quick test?
 - Restart your cinnamon, don't open anything.
 - Press `Windows + L`
 - Click on `Log` tab. 
 - Try slide the sliders (Make what causing the error).
 - Past results here.

Another question: When you slide the sliders, the label changes?

**Comment by didier-linux** [comment]
Hello Raphael,
That is a good news it works for you with LMDE4, thanks to have tested it
here is the result  :
[Qredshifterr.txt](https://github.com/raphaelquintao/QRedshift/files/6159652/Qredshifterr.txt)

When I slide the sliders, label values ar changing.  In spite, I installed the latest version today 1.5.5, I still have exactly the same bug. Don't hesitate to ask me for other tests

**Comment by raphaelquintao** [comment]
I cant figure out your problem.
I released the version 1.6.0 today, but i don't think it will work for you.


Try to install version 1.5.3 and lets see what happens:
* Remove the applet from panel.
* Go to `~/.local/share/cinnamon/applets`
* Delete the previous version of `qredshift@quintao`
* Download the [qredshift@quintao_1.5.3.zip](https://github.com/raphaelquintao/QRedshift/files/6174972/qredshift%40quintao_1.5.3.zip) and extract to `~/.local/share/cinnamon/applets`
* Delete the configs at `~/.cinnamon/configs/qredshift@quintao`

Let me know if works...

**Comment by didier-linux** [comment]
Hello Raphael,
unfortunately, update to 1.6 did not change anything
But installing the 1.5.3 version with the procedure you kindly gave me works perfectly, thank you very much Raphael ! 
So, conclusion is
* last version works on LMDE , you checked it successfully
* only the old 1.5.3 works on my computer
* it implies I have something wrong on my computer, maybe a conflict with other desklet with the last version ? 
I received by Email @NikoKrause @brownsr, I am not sure to have undertood, should I open a ticket for this issue with them ?
many thanks for the time you spent for me
yours sincerely,
      Didier

**Comment by mz1193** [comment]
For what it's worth, I had the exact same issue and similar (as in, nothing useful, sadly) log output on my end, and it's fixed by reverting to 1.5.3. I'm running Debian 11 (Bullseye) with Cinnamon 4.8.6

**Comment by didier-linux** [comment]
Thanks for this feedback, zara. Have you the possibility to check it easily on debian 10 ? It should work on debian10 since Raphael did successfully the test on LMDE4 which is the same as debian 10 with main contrib non-free backports activated and an additionnal mint repository. But even if it works on debian10, it will not explain why it does not work on my machine ...
       Didier

**Comment by mz1193** [comment]
> Thanks for this feedback, zara. Have you the possibility to check it easily on debian 10 ? It should work on debian10 since Raphael did successfully the test on LMDE4 which is the same as debian 10 with main contrib non-free backports activated and an additionnal mint repository. But even if it works on debian10, it will not explain why it does not work on my machine ...
> Didier

Unfortunately I don't have a machine with Debian 10 installed at the moment so I am unable to test it there, my apologies

**Comment by wavesurf432** [comment]
Hello there, I'm having the same issue with Linux Mint 19.3 (Cinnamon 4.4.8).

Clicking and dragging temperature or brightness (both Night & Day if I remember correct) causes QRedshift to glitch out. To solve the issue you have to reload QRedshift, then the correct temperature and/or brightness is present. Single clicks don't cause the application to bug out, only dragging side to side.

**Comment by Mar-tux** [comment]
Hello, 
same Problem here. I can confirm, that version 1.5.3 is the last one that works without bugs on LMDE 4. 
And what have i learned from this? Never, ever update a program that is working perfectly without a need. 

Thanks Raphael for the solution. :-)   And i absolutely like your applet! It is much better than redshift-gtk. 

Greetings

Markus

**Comment by raphaelquintao** [comment]
Hi!
Good news! I found the problem and will release a new version this week with more details. 
Everyone can update safely.

Regards!

**Comment by raphaelquintao** [comment]
Hi again!

As i said i found the problem, i don't know if everyone here is a dev, but i will explain what i noticed.
This applet works by calling redshift in one-shot mode, so when you drag the slider, its call redshift multiple times, in version 1.5.3 and all previous versions i call the redshift in a synchronous way, in 1.5.4 i change to a asynchronous call.
But i noticed that to many asynchronous calls on some computers can make the applet to crash in some mysterious way.
By the way its never happened on my computer (an i7), but i noticed that problem in a old Core 2 Duo that i was using.
So i suspect i will only happens in some slow computer or notebooks. 

Anyway i reverted the main call back to synchronous, the only problem is that the cinnamon will show the annoying message again: 
***This applet contains function calls that could potentially cause Cinnamon to crash or freeze***.

If you wanna try that before release you can donwload it here: [qredshift@quintao_1.7.0b.zip](https://github.com/raphaelquintao/QRedshift/files/6380084/qredshift%40quintao_1.7.0b.zip).
And follow the instructions mentioned on https://github.com/raphaelquintao/QRedshift/issues/31#issuecomment-803257032 to install.

I would appreciate some feedback. Maybe whoever is having this problem can tell me their hardware, to validate my guess.

Best Regards.

**Comment by didier-linux** [comment]
Hello Raphael

Excellent work ! I installed the beta version and it seems OK. I suggest you to let it works a few days on my computer in order to check it more deeply. I am not a dev but by reading you I have the feeling I understood that the only reason you did not first chose the synchronous way (synchronous with cinnamon clock?) is for not to get the warning message in spite the synchonous way seems to be the best one, what you did on this last beta version ?
Thanks to the power 1000 to give us this wonderful application ! Cinnamon should really integrate it as the default application
       Didier

**Comment by didier-linux** [comment]
Hello Raphael,
This last beta version is perfectly working since 3 days on my computer, for me it is OK
Regards,
     Didier

**Comment by wavesurf432** [comment]
Just updated to the latest version and everything seems to be working again. I haven't gone through the day to night transition yet, but if anything pops up I'll let you know.

As for hardware, I'm on a laptop from 2010 I believe.

Thanks again for the great applet - really wonderful.

**Comment by raphaelquintao** [comment]
So, i think i can safely close that thread.

Thanks everyone! 🍻
