### ISSUE TITLE
Not working in Fedora 35 Cinnamon

### ISSUE THREAD

**Issue by apolymen** [raphaelquintao/QRedshiftCinnamon#42]
I've used QRedshift in Linux Mint before and I really liked it. Now that I switched to Fedora 35 Cinnamon, I can't make it work.

I have removed both redshift and redshift-gtk packages that were installed out of the box and made sure there's no redshift.conf file. The applet appears in Fedora's Applets Manager but cannot be enabled. It shows a warning sign which says "This applet contains function calls that could potentially cause Cinnamon to crash or freeze. If you are experiencing crashes or freezing, please try removing it".

**Comment by raphaelquintao** [comment]
Never tested that on Fedora, i developed it on Debian and I'm sure it works in Ubuntu and Mint as well.
Maybe someday I can try to make it run, but I won't promise.
