### ISSUE TITLE
(1.7.2)  Smooth transition don't work (or should not apply) when you are in the night time-range

### ISSUE THREAD

**Issue by nicolasmol** [raphaelquintao/QRedshiftCinnamon#46]
Hi.
From recent update, done during the night hours range (user defined).
Firstly, I though that I would have to wait '5 minutes' (as I defined) and was ready to simply report you that the smooth transition should not apply within the night range.
But finally, after 5 minutes waiting, the transition did simply not happen.

To be clear: I won’t know until tomorrow evening if the transition works from day time to night time.  Here I’m talking only from within night time. 

(mint 20.3, cinnamon 5.2.7 )

**Comment by raphaelquintao** [comment]
I double-checked and it really had a bug. 
I submitted a version [1.7.3 ](https://github.com/linuxmint/cinnamon-spices-applets/pull/4450)that will fix this.
Any new bug you find please report it here.

Thanks for the report! 🍻

**Comment by raphaelquintao** [comment]
For the smooth transition works you need to have the auto update enabled and update interval as low a possible, you only need to change the update interval if you experiencing some lag, which only happens in very slow and old pcs.

**Comment by nicolasmol** [comment]
it's an hp laptop from 2020, no graphic card (intel cpu i7, 8 cores)

**Comment by raphaelquintao** [comment]
It will work just fine with auto update set at 5 seconds.
