### ISSUE TITLE
(1.7.2)  At midnight it's goes "day temperature"

### ISSUE THREAD

**Issue by nicolasmol** [raphaelquintao/QRedshiftCinnamon#47]
Amazing. Today when midnight passed, it switched to "day temperatures".
Impossible to set it back to "night temperatures"
![image](https://user-images.githubusercontent.com/61077647/187805571-578faf49-9284-4b9b-9a54-19a961b29892.png)

**Comment by raphaelquintao** [comment]
It will be fixed on version [1.73.](https://github.com/linuxmint/cinnamon-spices-applets/pull/4450) 
For now you can disable smooth transition and will work.
