### ISSUE TITLE
Location will not automatically update setting

### ISSUE THREAD

**Issue by trymeouteh** [raphaelquintao/QRedshiftCinnamon#51]
I use a VPN and I find that I have to go into the qRedshift settings every now and then and add my city latitude and longitude manually since qRedshift uses my IP address to get my location for the night time mode. But my IP address is not my actual locatio due to my VPN.

**Comment by mash-00** [comment]
Hi @trymeouteh ,
maybe you have overlooked this option:
![image](https://github.com/raphaelquintao/QRedshift/assets/61222732/53b2023a-53a4-4ae5-8587-6c7369bc3066)
I can confirm, if the option "Remote Location" is turned off, lat. and long. is used and works as expected.

Hence I think this issue can be closed.

BR
