### ISSUE TITLE
qredshift@quintao 1.7.3 completely stopped working on linux mint 21

### ISSUE THREAD

**Issue by sisa84** [raphaelquintao/QRedshiftCinnamon#52]
[xsession-errors.txt](https://github.com/raphaelquintao/QRedshift/files/9982926/xsession-errors.txt)

 * Applet version/Build date (Version 1.7.3)
 * Cinnamon version (Cinnamon 5.4.12)
 * Distribution - (Linux Mint 21) kernel 5.15.0-52-generic
 * Graphics hardware *and* driver used: 
    
    Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] (rev 01)
    GA107M Geforce RTX 3050 Ti Mobile

    nvidia-driver-520-open version 520.56.06-0ubuntu0.22.04.1

 * attached ~/.xsession-errors

**Issue**
the applet is completely broken, and does not change the kelvin of the screen. It's still possible to manually change the temperature from terminal (redshift -O 4500) but doing so now "staks" the effect: if I input the same command twice, the temperature goes first to 4500 and then get more red the second time.

**Steps to reproduce**
nothing really, the app is completely broken to me no matter what.

**Expected behaviour**
the gui should work

**Other information**
redshift-gtk is not installed. I have tried also the noveau graphic driver open source with no differences. No differences with reinstall either, nor with adjustment methods different from randr.

**Comment by sisa84** [comment]
I have checked on another PC with mint 20.3 and latest qredshift version, and the applet is completely broken there as well

**Comment by raphaelquintao** [comment]
Can you please run the command `which redshift-gtk` and show me the output?

**Comment by sisa84** [comment]
It does not appear to have an output?
![image](https://user-images.githubusercontent.com/117930353/204468591-02555780-c621-4238-aef5-a8569ec1aa60.png)

**Comment by FibroJedi** [comment]
@sisa84 depending on the NVIDIA driver, the brightness etc may be being overwritten by that part of `nvidia-settings`. It may be worth checking there because the two can "fight" from what I've been experimenting with.
![nvidia-color-correction](https://user-images.githubusercontent.com/69349920/204518324-f344fe1b-be8b-41e5-baff-56a13a6cdc73.jpg)

**Comment by sisa84** [comment]
Yes. Sadly it does not seems to respond with different gpus and different drivers.

**Comment by sisa84** [comment]
ok so the problem might be with redshift itself rather then with this applet as i get similar problems with the other redhift applett, i close the issue for now.

**Comment by sisa84** [comment]
Ok so I'm reopening this because on the other computer with linux (that i never use) qredshift is not working aswell, but redshift is from terminal. the strange thing is that redshift commands adds up. eg if i input `redshift -O 4500` twice the redness stacks, going to 2000 or so.

**Comment by sisa84** [comment]
ok nevermind problem lies with redshift.
