### ISSUE TITLE
Smooth transitions not working

### ISSUE THREAD

**Issue by 3coma3** [raphaelquintao/QRedshiftCinnamon#57]
On Linux Mint 21.1 with Cinnamon 5.6.8, QRedshift transitions instantly from day to night, even with the transition time set at 60 minutes. Otherwise everything working great! If there's something I can do to help debugging just let me know.

**Comment by raphaelquintao** [comment]
The update interval should be less as possible, and auto update need to be enabled.

**Comment by 3coma3** [comment]
> The update interval should be less as possible, and auto update need to be enabled.

Thanks for the reply @raphaelquintao, I had auto update and a 5 second interval. I'll try with the minimum of 3 and report back.
