### ISSUE TITLE
Smooth transition affects temperature, not brightness

### ISSUE THREAD

**Issue by jaymehta-g** [raphaelquintao/QRedshiftCinnamon#65]
When I reach the nighttime period, the screen gradually adjusts to the new temperature over the transition period, but the screen drops in brightness immediately. I assume the gradual transition should apply to both.

**Comment by K0-RR** [comment]
I can confirm this issue.

**Comment by raphaelquintao** [comment]
Will be fixed on version 2.0, that will be released in the following days.
