### ISSUE TITLE
Not available on linux mint as applet

### ISSUE THREAD

**Issue by kristof-linux** [raphaelquintao/QRedshiftCinnamon#68]
Hello,
I download with the download link and decompressed it in the right location, but it's not visible as applet.
By the way: i have alreadry redshift in the system. 
Please can you help to get your great applet working on my system?
Thx

![afbeelding](https://github.com/raphaelquintao/QRedshift/assets/58733661/066798d2-79fd-4d39-87e3-8c06f861c1ca)
![afbeelding](https://github.com/raphaelquintao/QRedshift/assets/58733661/a6fde8c3-f795-4f05-aa92-5d4957e01f54)

System:
  Kernel: 6.5.0-17-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 6.0.4 tk: GTK 3.24.33
    wm: muffin vt: 7 dm: LightDM 1.30.0 Distro: Linux Mint 21.3 Virginia base: Ubuntu 22.04 jammy
Machine:
  Type: Laptop System: LENOVO product: 21EB0073MB v: ThinkPad E14 Gen 4
    serial: <superuser required> Chassis: type: 10 serial: <superuser required>
  Mobo: LENOVO model: 21EB0073MB v: ThinkPad serial: <superuser required> UEFI: LENOVO
    v: R20ET38W (1.18 ) date: 09/18/2023
Battery:
  ID-1: BAT0 charge: 51.9 Wh (89.5%) condition: 58.0/57.0 Wh (101.8%) volts: 12.6 min: 11.5
    model: Celxpert LNV-5B11C73245 type: Li-poly serial: <filter> status: Discharging cycles: 7
CPU:
  Info: 6-core model: AMD Ryzen 5 5625U with Radeon Graphics bits: 64 type: MT MCP smt: enabled
    arch: Zen 3 rev: 0 cache: L1: 384 KiB L2: 3 MiB L3: 16 MiB
  Speed (MHz): avg: 933 high: 1622 min/max: 400/4388 cores: 1: 400 2: 400 3: 1622 4: 1397
    5: 1396 6: 1397 7: 400 8: 400 9: 1590 10: 400 11: 1396 12: 400 bogomips: 55095
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm
Graphics:
  Device-1: AMD Barcelo vendor: Lenovo driver: amdgpu v: kernel pcie: speed: 8 GT/s lanes: 16
    ports: active: eDP-1 empty: DP-1,HDMI-A-1 bus-ID: 05:00.0 chip-ID: 1002:15e7 class-ID: 0300
  Device-2: Chicony Integrated Camera type: USB driver: uvcvideo bus-ID: 1-3:2
    chip-ID: 04f2:b758 class-ID: fe01 serial: <filter>
  Display: x11 server: X.Org v: 1.21.1.4 driver: X: loaded: amdgpu,ati
    unloaded: fbdev,modesetting,vesa gpu: amdgpu display-ID: :0 screens: 1
  Screen-1: 0 s-res: 1920x1080 s-dpi: 96 s-size: 508x285mm (20.0x11.2") s-diag: 582mm (22.9")
  Monitor-1: eDP res: 1920x1080 hz: 60 dpi: 158 size: 309x174mm (12.2x6.9") diag: 355mm (14")
  OpenGL: renderer: RENOIR (renoir LLVM 15.0.7 DRM 3.54 6.5.0-17-generic)
    v: 4.6 Mesa 23.0.4-0ubuntu1~22.04.1 direct render: Yes
Audio:
  Device-1: AMD Renoir Radeon High Definition Audio vendor: Lenovo driver: snd_hda_intel v: kernel
    pcie: speed: 8 GT/s lanes: 16 bus-ID: 05:00.1 chip-ID: 1002:1637 class-ID: 0403
  Device-2: AMD Raven/Raven2/FireFlight/Renoir Audio Processor vendor: Lenovo driver: N/A pcie:
    speed: 8 GT/s lanes: 16 bus-ID: 05:00.5 chip-ID: 1022:15e2 class-ID: 0480
  Device-3: AMD Family 17h HD Audio vendor: Lenovo driver: snd_hda_intel v: kernel pcie:
    speed: 8 GT/s lanes: 16 bus-ID: 05:00.6 chip-ID: 1022:15e3 class-ID: 0403
  Sound Server-1: ALSA v: k6.5.0-17-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: no
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet vendor: Lenovo driver: r8169
    v: kernel pcie: speed: 2.5 GT/s lanes: 1 port: 2000 bus-ID: 02:00.0 chip-ID: 10ec:8168
    class-ID: 0200
  IF: enp2s0 state: down mac: <filter>
  Device-2: MEDIATEK MT7921 802.11ax PCI Express Wireless Network Adapter vendor: Lenovo
    driver: mt7921e v: kernel pcie: speed: 5 GT/s lanes: 1 bus-ID: 03:00.0 chip-ID: 14c3:7961
    class-ID: 0280
  IF: wlp3s0 state: up mac: <filter>
Bluetooth:
  Device-1: Foxconn / Hon Hai Wireless_Device type: USB driver: btusb v: 0.8 bus-ID: 3-4:3
    chip-ID: 0489:e0cd class-ID: e001 serial: <filter>
  Report: hciconfig ID: hci0 rfk-id: 1 state: up address: <filter> bt-v: 3.0 lmp-v: 5.2
    sub-v: 2202 hci-v: 5.2 rev: 915
Drives:
  Local Storage: total: 1.38 TiB used: 601.6 GiB (42.7%)
  ID-1: /dev/nvme0n1 vendor: Micron model: MTFDKCD512TFK size: 476.94 GiB speed: 63.2 Gb/s
    lanes: 4 type: SSD serial: <filter> rev: 7003V5LN temp: 24.9 C scheme: GPT
  ID-2: /dev/nvme1n1 vendor: Western Digital model: WD BLACK SN770 1TB size: 931.51 GiB
    speed: 63.2 Gb/s lanes: 4 type: SSD serial: <filter> rev: 731100WD temp: 30.9 C scheme: GPT
Partition:
  ID-1: / size: 915.82 GiB used: 36.54 GiB (4.0%) fs: ext4 dev: /dev/nvme1n1p1
  ID-2: /boot/efi size: 256 MiB used: 36.4 MiB (14.2%) fs: vfat dev: /dev/nvme0n1p1
Swap:
  ID-1: swap-1 type: file size: 2 GiB used: 0 KiB (0.0%) priority: -2 file: /swapfile
USB:
  Hub-1: 1-0:1 info: Hi-speed hub with single TT ports: 4 rev: 2.0 speed: 480 Mb/s
    chip-ID: 1d6b:0002 class-ID: 0900
  Device-1: 1-3:2 info: Chicony Integrated Camera type: Video driver: uvcvideo interfaces: 5
    rev: 2.0 speed: 480 Mb/s power: 500mA chip-ID: 04f2:b758 class-ID: fe01 serial: <filter>
  Hub-2: 2-0:1 info: Super-speed hub ports: 2 rev: 3.1 speed: 10 Gb/s chip-ID: 1d6b:0003
    class-ID: 0900
  Hub-3: 3-0:1 info: Hi-speed hub with single TT ports: 4 rev: 2.0 speed: 480 Mb/s
    chip-ID: 1d6b:0002 class-ID: 0900
  Device-1: 3-3:2 info: Shenzhen Goodix FingerPrint type: <vendor specific> driver: N/A
    interfaces: 1 rev: 2.0 speed: 12 Mb/s power: 100mA chip-ID: 27c6:550a class-ID: ff00
  Device-2: 3-4:3 info: Foxconn / Hon Hai Wireless_Device type: Bluetooth driver: btusb
    interfaces: 3 rev: 2.1 speed: 480 Mb/s power: 100mA chip-ID: 0489:e0cd class-ID: e001
    serial: <filter>
  Hub-4: 4-0:1 info: Super-speed hub ports: 2 rev: 3.1 speed: 10 Gb/s chip-ID: 1d6b:0003
    class-ID: 0900
Sensors:
  System Temperatures: cpu: 38.0 C mobo: N/A gpu: amdgpu temp: 37.0 C
  Fan Speeds (RPM): fan-1: 0 fan-2: 0
Repos:
  Packages: apt: 2460
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/apandada1-brightness-controller-jammy.list
    1: deb [signed-by=/etc/apt/keyrings/apandada1-brightness-controller-jammy.gpg] https: //ppa.launchpadcontent.net/apandada1/brightness-controller/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/appimagelauncher-team-stable-jammy.list
    1: deb [signed-by=/etc/apt/keyrings/appimagelauncher-team-stable-jammy.gpg] https: //ppa.launchpadcontent.net/appimagelauncher-team/stable/ubuntu jammy main
  Active apt repos in: /etc/apt/sources.list.d/google-chrome.list
    1: deb [arch=amd64] https: //dl.google.com/linux/chrome/deb/ stable main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http: //packages.linuxmint.com virginia main upstream import backport
    2: deb http: //archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
    3: deb http: //archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
    4: deb http: //archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
Info:
  Processes: 349 Uptime: 7m wakeups: 1 Memory: 14.45 GiB used: 2.76 GiB (19.1%) Init: systemd
  v: 249 runlevel: 5 Compilers: gcc: 11.4.0 alt: 11/12 Client: Cinnamon v: 6.0.4 inxi: 3.3.13

**Comment by raphaelquintao** [comment]
You looking for it in the wrong location. Go to settings -> applets.
