### ISSUE TITLE
Configurable step size when using shortcuts

### ISSUE THREAD

**Issue by CDeenen** [raphaelquintao/QRedshiftCinnamon#69]
Using shortcuts to, for example, increase the brightness, increases it by 1% for every keypress. Having to use the shortcut a lot to get a desired level is a bit annoying, while holding it down results in a slow increase that can take several seconds to complete during which the system is not accessible.
I don't need the fine adjustments, 10% per press would probably be sufficient. So a setting to configure the step size would be great.

**Comment by raphaelquintao** [comment]
Will be implement on version 2.0, that will be released in the following days.

**Comment by raphaelquintao** [comment]
@CDeenen The version 2.0.0 was reverted back on the repository. 
For now, if you want the latest version maintained by me you can follow these steps:

1. Download zip from [qredshift@quintao_2.0.0.zip](https://github.com/raphaelquintao/QRedshiftCinnamon/releases/download/v2.0.0/qredshift@quintao_2.0.0.zip).
2. Extract .zip archive to `~/.local/share/cinnamon/applets`.
3. Enable the applet in Cinnamon settings

**Comment by CDeenen** [comment]
Works great, thanks!
