### ISSUE TITLE
Wayland 'Adjustment Method' freezes Cinnamon

### ISSUE THREAD

**Issue by Splarkszter** [raphaelquintao/QRedshiftCinnamon#70]
When i select "Wayland" on adjustment method on the applet it completely freezes the entire system. Can't even access the virtual terminals so i have to force turn off the computer.

![image](https://github.com/raphaelquintao/QRedshiftCinnamon/assets/90066319/1c7c05c3-6858-46f5-b01c-0ce89b4bda88)

**Comment by raphaelquintao** [comment]
Wayland is not supported, current cinnamon compositor don't support that feature yet. 
For now i will completely disable the applet on wayland.

**Comment by Splarkszter** [comment]
Ok. Thank you :)
