### ISSUE TITLE
Bring "remote location" feature back

### ISSUE THREAD

**Issue by rkn45** [raphaelquintao/QRedshiftCinnamon#71]
Hey, I've been using your applet for quite a long time so first of all, thanks for all the work. 

Can you please bring the remote location back, I really liked that the day/night cycle automatically adjusted to the actual day/night. After the 2.0.0 update I had to manually readjust the night time so I don't get blasted with yellowness too early.

Once again, thank you for this extension and cheers.

**Comment by raphaelquintao** [comment]
I will bring it back! I will release a update today, hold on! =D

**Comment by raphaelquintao** [comment]
### Location is back an Better on version 2.0.1!
![](https://raw.githubusercontent.com/raphaelquintao/QRedshiftCinnamon/master/screenshots/screenshot.png)

Can you guys please check it out and give me a feedback?

#### Install with that command: 
```shell
curl https://github.com/raphaelquintao/QRedshiftCinnamon/raw/master/install.sh -sSfL | bash 
```

Notifying :  @Grydpype @Zach-Cameron @rkn45 @ovexro @claudiux

**Comment by claudiux** [comment]
@raphaelquintao v2.0.1 works very well. Many thanks to you!

**Comment by rkn45** [comment]
![image](https://github.com/raphaelquintao/QRedshiftCinnamon/assets/37614865/5ad24998-5dc8-4a9e-a076-92c5dcaee928)
v2.0.1 works as good as it did before the update, closing the issue. Thanks for the work!
