### ISSUE TITLE
Applet crashes when edit lat/long settings

### ISSUE THREAD

**Issue by geofausto** [raphaelquintao/QRedshiftCinnamon#72]
When I edit the latitude or longitude fields, the applet breaks, the screen goes black and the entire system crashes. To get around it, I have to delete the installed folder in /.local/share/cinnamon/applets and/or edit the applet configuration file for lat/long fields.

QRedshift version 2.0.3. It happens since version 2.0.0.

Linux Mint 21.3 x86_64 
Cinnamon 6.0.4
5.15.0-113-generic

**Comment by raphaelquintao** [comment]
What latitude and longitude you trying to use? 
Have you tried to change with the applet disabled?

**Comment by geofausto** [comment]
The problem happens when I type any character in the 'Latitude' or 'Longitude' field. For example, when changing coordinates by typing "-" everything freezes and the screen goes black. At first I thought the problem was only when typing "," or "." to decimal places. As I said, I currently make changes to .json configuration file. These changes are made instantly after save .json file.

I didn't test with the applet disabled.

![image](https://github.com/raphaelquintao/QRedshiftCinnamon/assets/7757383/3b2525d0-3bfd-40c8-99ce-5ab426c1553d)

**Comment by raphaelquintao** [comment]
I found it, happens when you type the `-`. 
I will fix it today.

Thanks for report.

**Comment by raphaelquintao** [comment]
Fixed in Version 2.0.4
Let me know if it works for you.

**Comment by geofausto** [comment]
Ok. It's working!
