### ISSUE TITLE
Incomplete translation

### ISSUE THREAD

**Issue by 0HAg0** [raphaelquintao/QRedshiftCinnamon#73]
The da.po was incomplete, so i generated a .POT file, and made and new translation.
I have replaced the old .po file, with the new.

How can i Make QRedshiftCinnamon use it, in stead of the old?
I like to contribute with this new translation. How can i do that?

**Comment by raphaelquintao** [comment]
Copy  the new generate `.po` to `~/.local/share/cinnamon/applets/qredshift@quintao/po` and overwrite it.
Right click on the applet and click on recompile translations.
![image](https://github.com/raphaelquintao/QRedshiftCinnamon/assets/2568375/e02d0592-902f-460b-ae70-e99798c9217b)

If you know how to use git you can submit a pull request here and i will update it on the repository, if you don't, just upload it here and i can put that on the newer versions.

**Comment by 0HAg0** [comment]
Thank you, for respond. Danish translation for QRedshift Cinnamon 2.0.3, is attached.

Note: The path in "When updating to a new version make sure you reset the configs to default by deleting the ~/.cinnamon/configs/qredshift@quintao/qredshift@quintao.json." is wrong. The right path is: ~/.config/cinnamon/spices/qredshift@quintao/qredshift@quintao.json.

I have corrected this, in the Danish translation.

[da.zip](https://github.com/user-attachments/files/16179015/da.zip)

**Comment by raphaelquintao** [comment]
Thanks! 🍻
