### ISSUE TITLE
How do i change the color of main window?

### ISSUE THREAD

**Issue by DJ-Dav** [raphaelquintao/QRedshiftCinnamon#79]
Clicking the applet on by toolbar opens a control window that appears to always be in light mode. I use this tool to protect my eyes, please make it possible to not flash-bang myself when turning it on. (Config window respects dark mode, only applet does not)
![image](https://github.com/user-attachments/assets/27543391-8409-4c14-af11-d6c4d0e0f530)

**Comment by raphaelquintao** [comment]
Its your theme, try to change it.
